3300 #!/usr/bin/perl -w
3301 
3302 # Generate vectors.S, the trap/interrupt entry points.
3303 # There has to be one entry point per interrupt number
3304 # since otherwise there's no way for trap() to discover
3305 # the interrupt number.
3306 
3307 print "# generated by vectors.pl - do not edit\n";
3308 print "# handlers\n";
3309 print ".globl alltraps\n";
3310 for(my $i = 0; $i < 256; $i++){
3311     print ".globl vector$i\n";
3312     print "vector$i:\n";
3313     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
3314         print "  pushl \$0\n";
3315     }
3316     print "  pushl \$$i\n";
3317     print "  jmp alltraps\n";
3318 }
3319 
3320 print "\n# vector table\n";
3321 print ".data\n";
3322 print ".globl vectors\n";
3323 print "vectors:\n";
3324 for(my $i = 0; $i < 256; $i++){
3325     print "  .long vector$i\n";
3326 }
3327 
3328 # sample output:
3329 #   # handlers
3330 #   .globl alltraps
3331 #   .globl vector0
3332 #   vector0:
3333 #     pushl $0
3334 #     pushl $0
3335 #     jmp alltraps
3336 #   ...
3337 #
3338 #   # vector table
3339 #   .data
3340 #   .globl vectors
3341 #   vectors:
3342 #     .long vector0
3343 #     .long vector1
3344 #     .long vector2
3345 #   ...
3346 
3347 
3348 
3349 
